import Head from "next/head";
import React from "react";
import ChatBox from "../../../components/chat-box";
import ChatList from "../../../components/chat-list";
import Header from "../../../components/layout/Header";

const Chat = () => {
  return (
    <>
      <Head>
        <title>Goodjobs-Chatting</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-screen bg-gray-100 '>
        <Header />
        <div className='w-full flex justify-center mt-6 mb-6 h-4/5'>
          <div className='w-4/5 content-center max-w-screen-xl flex'>
            <div className='basis-1/3'>
              <ChatList />
            </div>

            <div className='basis-2/3'>
              <ChatBox />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Chat;
