import Head from "next/head";
import React, {useEffect} from "react";
import Header from "../../components/layout/Header";
import Footer from "../../components/layout/Footer";
import PostDetail from "../../components/posts/PostDetail";
import {useRouter} from "next/router";
import {route} from "next/dist/server/router";

const Post = () => {

    return (
       <>
           <Head>
               <title>Goodjobs</title>
               <meta name='description' content='Generated by create next app' />
               <link rel='icon' href='/favicon.ico' />
           </Head>

           <main className="bg-gray-100">
               <Header />
               <PostDetail />
               <Footer />
           </main>
       </>
    )
}

export default Post;